### ISSUE TITLE
Split MainRepository and ChatsDao

### ISSUE THREAD

**Issue by odaridavid** [Kod4black/TalkSelf#15]
Split `MainRepository` to more granular repositories named according to their purpose e.g `ChatRepository`, `UserRepository`

This is to prevent bloating of that one repository and single responsibility concerns, same could be said for the `ChatsDao`

**Comment by Carrieukie** [comment]
Hi @odaridavid. Has issue been worked on yet? I've searched for MainRepository and it's not there.

**Comment by odaridavid** [comment]
Ah then I probably already fixed it, I'll close it
